import type { AppConfig, LoadState, TemperatureUnit } from "../shared/types";
import { weatherDescription } from "../lib/weatherPresentation";
import { WeatherIcon } from "./WeatherIcon";
const number=(value:number)=>Math.round(value);
const time=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit"}).format(new Date(value)):"—";
const day=(value:string)=>new Intl.DateTimeFormat("en-US",{weekday:"short"}).format(new Date(`${value}T12:00:00`));
const date=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(`${value}T12:00:00`));
const direction=(degrees:number|null)=>degrees===null?"—":["N","NE","E","SE","S","SW","W","NW"][Math.round(degrees/45)%8];

export function WeatherDashboard({state,config,onRefresh,onUnits}:{state:LoadState;config:AppConfig|null;onRefresh:()=>void;onUnits:(unit:TemperatureUnit)=>void}){
  if(state.phase==="loading"&&!state.snapshot)return <StatePanel kind="loading" title="Reading the sky" detail="Contacting the weather source and checking local cache…"/>;
  if(state.phase==="error"&&!state.snapshot)return <StatePanel kind="error" title="Weather is temporarily unavailable" detail={state.error??"No live or cached forecast is available."} action={onRefresh}/>;
  const snapshot=state.snapshot!;const data=snapshot.data;const current=data.current;const today=data.forecast[0];
  return <div className="weather-dashboard">
    {(state.phase==="stale"||state.phase==="error")&&<div className="stale-banner" role="status"><strong>Showing saved forecast</strong><span>{state.error??"The cached forecast is older than the configured refresh window."}</span></div>}
    <section className="current-card">
      <div className="current-copy"><p className="eyebrow">CURRENT CONDITIONS</p><h2>{data.location_name}</h2><div className="current-reading">{current?<><WeatherIcon code={current.weather_code} large/><strong>{number(current.temperature)}<sup>{data.temperature_symbol}</sup></strong></>:<strong className="unavailable">Current reading unavailable</strong>}</div><p className="condition-name">{current?weatherDescription(current.weather_code):weatherDescription(today.weather_code)}</p>{current?.apparent_temperature!=null&&<p className="feels">Feels like {number(current.apparent_temperature)}{data.temperature_symbol}</p>}</div>
      <div className="today-facts"><Fact label="TODAY" value={`${number(today.high)}° / ${number(today.low)}°`}/><Fact label="PRECIPITATION" value={today.precipitation_probability==null?"—":`${today.precipitation_probability}%`}/><Fact label="WIND" value={`${direction(current?.wind_direction??today.wind_direction)} ${number(current?.wind_speed??today.wind_speed??0)} ${data.wind_unit}`}/><div className="sun-cycle"><Fact label="SUNRISE" value={time(today.sunrise)}/><span className="sun-line"><i/></span><Fact label="SUNSET" value={time(today.sunset)}/></div></div>
    </section>
    <section className="forecast-section"><div className="section-heading"><div><p className="eyebrow">OUTLOOK</p><h3>Ten-day forecast</h3></div><span>Newberry local time</span></div><div className="forecast-grid">{data.forecast.map((item,index)=><article className={index===0?"today":""} key={item.date}><header><strong>{index===0?"Today":day(item.date)}</strong><small>{date(item.date)}</small></header><WeatherIcon code={item.weather_code}/><p className="forecast-condition">{weatherDescription(item.weather_code)}</p><div className="temperatures"><strong>{number(item.high)}°</strong><span>{number(item.low)}°</span></div><footer><span>☂ {item.precipitation_probability??0}%</span><span>{direction(item.wind_direction)} {item.wind_speed==null?"—":number(item.wind_speed)}</span></footer></article>)}</div></section>
    <footer className="source-footer"><div><span className={`source-dot ${snapshot.freshness}`}/><strong>{snapshot.freshness==="fresh"?"Source online":"Cached source"}</strong><span>Weather data available</span></div><div className="unit-switch" aria-label="Temperature units"><button className={data.temperature_unit==="fahrenheit"?"active":""} onClick={()=>onUnits("fahrenheit")}>°F</button><button className={data.temperature_unit==="celsius"?"active":""} onClick={()=>onUnits("celsius")}>°C</button></div><details><summary>Source details</summary><p>{data.source_name} · fetched {new Date(data.fetched_at).toLocaleString()} · refresh interval {config?.refresh_interval_minutes??30} minutes</p></details><button className="refresh-button" disabled={state.phase==="refreshing"} onClick={onRefresh}>{state.phase==="refreshing"?"Refreshing…":"Refresh weather"}</button></footer>
  </div>
}
function Fact({label,value}:{label:string;value:string}){return <div className="fact"><small>{label}</small><strong>{value}</strong></div>}
function StatePanel({kind,title,detail,action}:{kind:"loading"|"error";title:string;detail:string;action?:()=>void}){return <section className={`state-panel ${kind}`} role={kind==="error"?"alert":"status"}><span>{kind==="loading"?"◌":"!"}</span><p className="eyebrow">{kind==="loading"?"WEATHER SOURCE":"SOURCE ERROR"}</p><h2>{title}</h2><p>{detail}</p>{action&&<button onClick={action}>Try again</button>}</section>}
